# Generated by Django 4.0.2 on 2022-02-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Boid', models.BigIntegerField()),
                ('apply_kitta', models.IntegerField(default=10)),
                ('Crn', models.CharField(max_length=8)),
                ('Pin', models.IntegerField()),
            ],
        ),
    ]
